### ISSUE TITLE
[Linux] Does not work with native Steam and Proton.

### ISSUE THREAD

**Issue by dragnod0** [satisfactorymodding/SatisfactoryModManager#104]
I use the native Linux Steam Client and Proton 5.0-10. The Game runs fine with that. 
But the Modlauncher search for Lutris installed Steam and Epic client. The Launcher find the path from the installed Satisfactory but says  "No Satisfactory installs Found"

This is the Debug file:
```
2021-04-25 02:19:26:088	[INFO]	Set debug mode to false
2021-04-25 02:19:34:497	[DEBUG]	Epic Games Launcher is not installed in Lutris - Cyberpunk 2077
2021-04-25 02:19:34:497	[DEBUG]	Lutris game Space Engineers has null directory.
2021-04-25 02:19:34:498	[DEBUG]	Epic Games Launcher is not installed in Lutris - Ubisoft Connect
2021-04-25 02:19:34:498	[DEBUG]	Legendary is not installed
2021-04-25 02:19:34:498	[DEBUG]	Steam is not installed
2021-04-25 02:19:34:507	[ERROR]	BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

Trace
Error: BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

    at BatchCluster.enqueueTask (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/batch-cluster/dist/BatchCluster.js:232:25)
    at /tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/ExifTool.js:386:83
    at Object.<anonymous> (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:49:42)
    at step (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:33:23)
    at Object.next (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:53)
    at /tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:4:12)
    at g (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:43:34)
    at Object.<anonymous> (/tmp/.mount_SatisfiAcze1/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:55:47)
2021-04-25 02:20:06:305	[INFO]	Set debug mode to false
2021-04-25 02:20:07:509	[DEBUG]	Epic Games Launcher is not installed in Lutris - Cyberpunk 2077
2021-04-25 02:20:07:509	[DEBUG]	Lutris game Space Engineers has null directory.
2021-04-25 02:20:07:509	[DEBUG]	Epic Games Launcher is not installed in Lutris - Ubisoft Connect
2021-04-25 02:20:07:509	[DEBUG]	Legendary is not installed
2021-04-25 02:20:07:509	[DEBUG]	Steam is not installed
2021-04-25 02:20:07:518	[ERROR]	BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

Trace
Error: BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

    at BatchCluster.enqueueTask (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/batch-cluster/dist/BatchCluster.js:232:25)
    at /tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/ExifTool.js:386:83
    at Object.<anonymous> (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:49:42)
    at step (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:33:23)
    at Object.next (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:53)
    at /tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:4:12)
    at g (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:43:34)
    at Object.<anonymous> (/tmp/.mount_SatisfbegmzT/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:55:47)
2021-04-25 02:23:32:250	[INFO]	Set debug mode to false
2021-04-25 02:23:36:973	[DEBUG]	Epic Games Launcher is not installed in Lutris - Cyberpunk 2077
2021-04-25 02:23:36:973	[DEBUG]	Lutris game Space Engineers has null directory.
2021-04-25 02:23:36:973	[DEBUG]	Epic Games Launcher is not installed in Lutris - Ubisoft Connect
2021-04-25 02:23:36:973	[DEBUG]	Legendary is not installed
2021-04-25 02:23:36:974	[DEBUG]	Steam is not installed
2021-04-25 02:23:36:982	[ERROR]	BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

Trace
Error: BatchCluster has ended, cannot enqueue -json
-struct
-fast
-coordFormat
%.8f
-*Duration*#
-GPS*#
-Orientation#
-all
-charset
filename=utf8
/mnt/Games2/SteamLibrary/steamapps/common/Satisfactory/FactoryGame.exe
-ignoreMinorErrors
-execute

    at BatchCluster.enqueueTask (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/batch-cluster/dist/BatchCluster.js:232:25)
    at /tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/ExifTool.js:386:83
    at Object.<anonymous> (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:49:42)
    at step (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:33:23)
    at Object.next (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:53)
    at /tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:4:12)
    at g (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:43:34)
    at Object.<anonymous> (/tmp/.mount_Satisf8ofTMx/resources/app.asar/node_modules/exiftool-vendored/dist/AsyncRetry.js:55:47)
```

**Comment by mircearoata** [comment]
This is an issue with exiftool that I couldn't find any fix for, only a couple of other issues on github but with no solution either. In SMM v2.6.0 however it no longer uses exiftool, so the issue is gone as well.
