### ISSUE TITLE
Experimental Update 5 progress

### ISSUE THREAD

**Issue by debian-user-france1** [satisfactorymodding/SatisfactoryModManager#128]
I couldn't find much about the Update 5 progress of SMM on the Discord server so that's why I ask. I didn't try with Update 4 so I don't know if the mod is working at all - but I get following error with one mod when I try to load it: Plugin FicsItNetworks failed to load because module FicsItNetowks could not be loaded. (best ever)
There may be n os error or the module may not he prob. set up.

Then the game closes. If I start satisfactory with the SMM it doesn't show me that it's running - only for like 2 seconds.

Any other mod I tested just crashed the game without any error message

Why is this happening?
Cheers

Using Manjaro Linux with Steam, Proton experimental and newest Satisfactory experimental version

**Comment by debian-user-france1** [comment]
Lutris wasn't installed

**Comment by debian-user-france1** [comment]
```
2021-11-15 18:41:36:787	[INFO]	Set debug mode to false
2021-11-15 18:41:37:737	[ERROR]	Command failed: lutris -lj
Trace
Error: Command failed: lutris -lj
    at checkExecSyncError (child_process.js:625:11)
    at Object.execSync (child_process.js:661:15)
    at Object.execSync (electron/js2c/asar_bundle.js:5:12288)
    at Object.getInstalls (/tmp/.mount_SatisfeXgN92/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/lutrisEpic.js:18:56)
    at Object.getInstalls (/tmp/.mount_SatisfeXgN92/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/index.js:10:37)
    at getInstalls (/tmp/.mount_SatisfeXgN92/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/index.js:11:24)
    at file:///tmp/.mount_SatisfeXgN92/resources/app.asar/dist/electron/renderer.js:2:326930
    at p (file:///tmp/.mount_SatisfeXgN92/resources/app.asar/dist/electron/renderer.js:2:2289973)
    at Generator._invoke (file:///tmp/.mount_SatisfeXgN92/resources/app.asar/dist/electron/renderer.js:2:2289761)
    at Generator.next (file:///tmp/.mount_SatisfeXgN92/resources/app.asar/dist/electron/renderer.js:2:2290398)
2021-11-15 18:41:37:737	[DEBUG]	Legendary is not installed
2021-11-15 18:41:38:197	[DEBUG]	Steam-flatpak is not installed
2021-11-15 18:41:38:295	[DEBUG]	Setting profile to vanilla
2021-11-15 18:41:38:358	[DEBUG]	install: [], uninstall: [], enable: [], disable: [], update: []
2021-11-15 18:41:38:360	[DEBUG]	Items: {}
2021-11-15 18:41:38:371	[DEBUG]	Mismatches: {"install":{},"uninstall":[]}
2021-11-15 18:43:27:804	[DEBUG]	Setting profile to mods
2021-11-15 18:43:27:973	[DEBUG]	install: [], uninstall: [], enable: [], disable: [], update: []
2021-11-15 18:43:32:596	[DEBUG]	Validating FactoryGame
2021-11-15 18:43:32:596	[DEBUG]	Validating SML
2021-11-15 18:43:32:598	[DEBUG]	Items: {"SML":"3.1.1"}
2021-11-15 18:43:32:598	[DEBUG]	Mismatches: {"install":{"SML":"3.1.1"},"uninstall":[]}
2021-11-15 18:43:32:599	[DEBUG]	Copying SML to Satisfactory install
2021-11-15 18:43:32:599	[DEBUG]	Installing SML@3.1.1
2021-11-15 18:43:41:638	[INFO]	Enabling FicsItNetworks
2021-11-15 18:43:41:736	[DEBUG]	install: [], uninstall: [], enable: [FicsItNetworks], disable: [], update: []
2021-11-15 18:43:41:741	[DEBUG]	Validating FactoryGame
2021-11-15 18:43:41:741	[DEBUG]	Validating FicsItNetworks
2021-11-15 18:43:57:072	[DEBUG]	Validating SML
2021-11-15 18:43:57:072	[DEBUG]	Validating SML
2021-11-15 18:43:57:072	[DEBUG]	Items: {"SML":"3.1.1","FicsItNetworks":"0.3.3"}
2021-11-15 18:43:57:073	[DEBUG]	Mismatches: {"install":{"FicsItNetworks":"0.3.3"},"uninstall":[]}
2021-11-15 18:43:57:078	[DEBUG]	Copying FicsItNetworks@0.3.3 to Satisfactory install
2021-11-15 18:46:42:675	[DEBUG]	Validating FicsItNetworks
2021-11-15 18:46:42:675	[DEBUG]	Validating SML
2021-11-15 18:46:42:676	[DEBUG]	Validating FactoryGame
2021-11-15 18:46:42:676	[DEBUG]	Validating SML
2021-11-15 18:51:43:674	[DEBUG]	Validating FicsItNetworks
2021-11-15 18:51:43:675	[DEBUG]	Validating SML
2021-11-15 18:51:43:676	[DEBUG]	Validating FactoryGame
2021-11-15 18:51:43:676	[DEBUG]	Validating SML
2021-11-15 18:56:44:355	[DEBUG]	Validating FicsItNetworks
2021-11-15 18:56:44:355	[DEBUG]	Validating SML
2021-11-15 18:56:44:355	[DEBUG]	Validating FactoryGame
2021-11-15 18:56:44:355	[DEBUG]	Validating SML
2021-11-15 19:01:45:082	[DEBUG]	Validating FicsItNetworks
2021-11-15 19:01:45:083	[DEBUG]	Validating SML
2021-11-15 19:01:45:083	[DEBUG]	Validating FactoryGame
2021-11-15 19:01:45:083	[DEBUG]	Validating SML
2021-11-15 19:06:45:579	[DEBUG]	Validating FicsItNetworks
2021-11-15 19:06:45:580	[DEBUG]	Validating SML
2021-11-15 19:06:45:581	[DEBUG]	Validating FactoryGame
2021-11-15 19:06:45:581	[DEBUG]	Validating SML
2021-11-15 19:09:54:638	[INFO]	Disabling FicsItNetworks
2021-11-15 19:09:54:743	[DEBUG]	install: [], uninstall: [], enable: [], disable: [FicsItNetworks], update: []
2021-11-15 19:09:54:745	[DEBUG]	Validating FactoryGame
2021-11-15 19:09:54:745	[DEBUG]	Validating SML
2021-11-15 19:09:54:745	[DEBUG]	Items: {"SML":"3.1.1"}
2021-11-15 19:09:54:746	[DEBUG]	Mismatches: {"install":{},"uninstall":["FicsItNetworks"]}
2021-11-15 19:09:54:747	[DEBUG]	Removing FicsItNetworks from Satisfactory install
2021-11-15 19:09:58:386	[INFO]	Enabling LogisticDrones
2021-11-15 19:09:58:479	[DEBUG]	install: [], uninstall: [], enable: [LogisticDrones], disable: [], update: []
2021-11-15 19:09:58:480	[DEBUG]	Validating FactoryGame
2021-11-15 19:09:58:480	[DEBUG]	Validating LogisticDrones
2021-11-15 19:09:58:652	[DEBUG]	Validating SML
2021-11-15 19:09:58:652	[DEBUG]	Validating SML
2021-11-15 19:09:58:652	[DEBUG]	Items: {"SML":"3.1.1","LogisticDrones":"1.0.0"}
2021-11-15 19:09:58:653	[DEBUG]	Mismatches: {"install":{"LogisticDrones":"1.0.0"},"uninstall":[]}
2021-11-15 19:09:58:653	[DEBUG]	Copying LogisticDrones@1.0.0 to Satisfactory install
2021-11-15 19:11:01:831	[DEBUG]	install: [], uninstall: [SML], enable: [], disable: [], update: []
2021-11-15 19:11:01:832	[DEBUG]	Validating FactoryGame
2021-11-15 19:11:01:832	[DEBUG]	Validating SML
2021-11-15 19:11:01:832	[DEBUG]	Validating LogisticDrones
2021-11-15 19:11:01:832	[DEBUG]	Items: {"SML":"3.1.1","LogisticDrones":"1.0.0"}
2021-11-15 19:11:01:833	[DEBUG]	Mismatches: {"install":{},"uninstall":[]}
```

**Comment by Ryder17z** [comment]
If you checked the modding discord, how did you miss that mods are not currently supported on experimental version?

You need to use Early Access version if you want mods to work at the moment.

**Comment by gOOvER** [comment]
EA of satisfacrory

**Comment by debian-user-france1** [comment]
And when could that come out?

**Comment by Ryder17z** [comment]
> And when could that come out?

Early Access is the "not experimental game version". 

Update5 goes live for Early Access on November 23 probably.

I'm guessing 1-2 weeks after that mods would be working properly, but I'm just guessing.

**Comment by mircearoata** [comment]
SML was updated on the November 23rd. SMM did not require an update because it simply copies files to where they should go. The compatibility check for mods was also updated in v2.6.0

**Comment by debian-user-france1** [comment]
Ok thanks anyway
