### ISSUE TITLE
Unexpected error while downloading file https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/download/v3.4.0/SML.zip: connect ETIMEDOUT 20.205.243.166:443

### ISSUE THREAD

**Issue by Coder-HHN** [satisfactorymodding/SatisfactoryModManager#169]
When I switch on a VPN, I can access the web https://ficsit.app/
but I still can't download any mod. 

Unexpected error while downloading file https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/download/v3.4.0/SML.zip: connect ETIMEDOUT 20.205.243.166:443. Trace:
RequestError: connect ETIMEDOUT 20.205.243.166:443
at ClientRequest.<anonymous> (file:///D:/Game/Satisfactory/resources/app.asar/dist/electron/renderer.js:197:105991)
at Object.onceWrapper (node:events:514:26)
at ClientRequest.emit (node:events:406:35)
at ClientRequest.t.emit (file:///D:/Game/Satisfactory/resources/app.asar/dist/electron/renderer.js:197:75467)
at TLSSocket.socketErrorListener (node:_http_client:447:9)
at TLSSocket.emit (node:events:394:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at __node_internal_captureLargerStackTrace (node:internal/errors:463:5)
at __node_internal_exceptionWithHostPort (node:internal/errors:641:12)
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
Seems wrong? Generate debug info and send it together with this error message
over on the modding discord in #help-using-mods

**Comment by mircearoata** [comment]
SML releases are now hosted on ficsit.app, like all other mods, so this should no longer be an issue

**Comment by Coder-HHN** [comment]
你好，来信已收到，将尽快回复。谢谢。
