### ISSUE TITLE
Error when updating SMM 2.2.1.0

### ISSUE THREAD

**Issue by staratnight** [satisfactorymodding/SatisfactoryModManager#76]
When starting SMM it will automatically update itself. 
The download speed is horribly low (16KB/sec instead of possible 10MB/sec). After a while (anywhere between 13% and 25% status) the download stops and an error is shown:

```
Error
Error while checking for SMM updates: Error: net::ERR_CONNECTION_RESET
at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6395)
at SimpleURLLoaderWrapper.emit (events.js:223:5)
Seems wrong? Generate debug info and send it over on the modding discord in #help-using-mods
```

I do not have any problems with dowloads in general or updating other apps (like Satisfactory itself via Epic).
Any idea?

**Comment by staratnight** [comment]
Today it "just works". I don't know what it was but obviously it had nothing to do with SMM itself.
