### ISSUE TITLE
Doesn't attach payload to game process on Manjaro

### ISSUE THREAD

**Issue by Ryder17z** [satisfactorymodding/SatisfactoryModManager#77]
i followed the suggestion of PR 5 from the bootstrapper repo. switched profiles back and forth, it doesn't help. I don't know where the issue lies. Launch options has been set. correctly too.

**Comment by sparr** [comment]
I, too, am on Manjaro, and can't get SMM to launch the game using any mods. Here's a debug log with just one mod "installed":

```
2020-12-08 21:12:54:427	[INFO]	Set debug mode to false
2020-12-08 21:12:54:647	[INFO]	Set debug mode to true
2020-12-08 21:12:56:700	[DEBUG]	Steam-flatpak is not installed
2020-12-08 21:12:56:759	[DEBUG]	Setting profile to modded
2020-12-08 21:12:56:805	[DEBUG]	install: [], uninstall: [], update: []
2020-12-08 21:13:04:222	[DEBUG]	Validating SML
2020-12-08 21:13:04:223	[DEBUG]	Validating FactoryGame
2020-12-08 21:13:04:223	[DEBUG]	Validating bootstrapper
2020-12-08 21:13:04:223	[DEBUG]	Validating SmartFoundations
2020-12-08 21:13:04:223	[DEBUG]	Items: {"SmartFoundations":"0.11.0","SML":"2.2.1","bootstrapper":"2.0.11"}
2020-12-08 21:13:04:234	[DEBUG]	Mismatches: {"install":{},"uninstall":[]}
2020-12-08 21:13:04:280	[ERROR]	ENOENT: no such file or directory, open '/home/sparr/.steam/steam/userdata/ac/config/localconfig.vdf'
Trace
Error: ENOENT: no such file or directory, open '/home/sparr/.steam/steam/userdata/ac/config/localconfig.vdf'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at /tmp/.mount_SatisfeolF8G/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/steam.js:25:65
    at Array.forEachAsync (/tmp/.mount_SatisfeolF8G/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/utils.js:155:15)
    at async SatisfactoryInstall.setupSteam (/tmp/.mount_SatisfeolF8G/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/steam.js:22:5)
    at async Promise.all (index 0)
2020-12-08 21:13:08:974	[DEBUG]	Validating SmartFoundations
2020-12-08 21:13:08:978	[DEBUG]	Validating SML
2020-12-08 21:13:08:980	[DEBUG]	Validating FactoryGame
2020-12-08 21:13:08:980	[DEBUG]	Validating bootstrapper
2020-12-08 21:13:08:981	[DEBUG]	Validating FactoryGame
```

**Comment by sparr** [comment]
A symlink from `STEAM LIBRARY FOLDER/userdata/9994904/config` to `/home/sparr/.steam/steam/userdata/ac/config/localconfig.vdf` gets rid of the error messages and then SMM modifies the file (I forgot to make a backup to diff, so now I'm reinstalling to get the original), but this leads to Satisfactory not being launchable from Steam or SMM, there's no visible effect to attempting to launch.

**Comment by BlobCodes** [comment]
Had the same issue, but found a way to solve it (comment at [aurweb](https://aur.archlinux.org/packages/satisfactory-mod-manager/) from laurinneff).

There seems to be a problem with the xinput dll.
Source: https://github.com/satisfactorymodding/SatisfactoryModBootstrapper/pull/5

Fix:
Download https://github.com/satisfactorymodding/SatisfactoryModBootstrapper/files/5472216/xinput1_3.zip
Unzip to ~/.cache/SatisfactoryModManager/downloadCache/bootstrapperVersions/2.0.11
Change to vanilla profile and back

**Comment by Ryder17z** [comment]
for me the issue was an incorrect copy operation. (automatic copy doesn't work)

Visually the operation completed successfully, but in reality, the files did not copy over.
This is a bug in XFCE i believe.

**Comment by TRPB** [comment]
this isn't working for me. If I override xinput1_3.dll, the game won't launch at all. do I need a different dll for the experimental branch with the engine upgrade?

**Comment by mircearoata** [comment]
Mods are not currently compatible with Experimental, because of the engine upgrade. You need to wait for SML to be updated, then for mods to be updated.

**Comment by Ryder17z** [comment]
comments below the last one i made (on Jan 9) can be considered invalid. I just forgot to close the issue as copying the files again solved the issue.
