### ISSUE TITLE
Not working on linux without lutris installed

### ISSUE THREAD

**Issue by RononDex** [satisfactorymodding/SatisfactoryModManager#96]
When launching the SMM on linux (using the .AppImage) I get the following error 
![image](https://user-images.githubusercontent.com/2249071/114667525-da6b7100-9cff-11eb-9e81-23d7e335d931.png)

This is with Steam closed and no process of steam is running.

The relevant logfile:
```
2021-04-14 08:58:59:004	[INFO]	Set debug mode to false
2021-04-14 08:59:05:931	[INFO]	Set debug mode to false
2021-04-14 08:59:06:742	[ERROR]	Command failed: lutris -lj
Trace
Error: Command failed: lutris -lj
    at checkExecSyncError (child_process.js:625:11)
    at Object.execSync (child_process.js:661:15)
    at Object.execSync (electron/js2c/asar_bundle.js:5:12059)
    at Object.getInstalls (/tmp/.mount_SatisfdKtZDZ/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/lutrisEpic.js:19:56)
    at Object.getInstalls (/tmp/.mount_SatisfdKtZDZ/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/linux/index.js:10:37)
    at getInstalls (/tmp/.mount_SatisfdKtZDZ/resources/app.asar/node_modules/satisfactory-mod-manager-api/lib/installfinders/index.js:11:24)
    at file:///tmp/.mount_SatisfdKtZDZ/resources/app.asar/dist/electron/renderer.js:2:122761
    at s (file:///tmp/.mount_SatisfdKtZDZ/resources/app.asar/dist/electron/renderer.js:2:2052947)
    at Generator._invoke (file:///tmp/.mount_SatisfdKtZDZ/resources/app.asar/dist/electron/renderer.js:2:2052735)
    at Generator.next (file:///tmp/.mount_SatisfdKtZDZ/resources/app.asar/dist/electron/renderer.js:2:2053372)
2021-04-14 08:59:06:742	[DEBUG]	Legendary is not installed
2021-04-14 08:59:07:049	[DEBUG]	Steam-flatpak is not installed
2021-04-14 08:59:07:240	[DEBUG]	Setting profile to modded
2021-04-14 08:59:08:076	[DEBUG]	install: [], uninstall: [], update: []
2021-04-14 08:59:08:077	[DEBUG]	Items: {}
2021-04-14 08:59:08:080	[DEBUG]	Mismatches: {"install":{},"uninstall":[]}
```

As it shows it seems to acccess / assume lutris is installed, which it is not on my setup ( I use steam with proton).

**Comment by RononDex** [comment]
From debuggin in the discord server, it apepars it is caused by SML identifying a local msteams instance as steam. If msteams is open it thinks steam is running and errors.
It has nothing to do with lutris.

After closing msteams it works

**Comment by mircearoata** [comment]
Changing the DLLOVERRIDES is no longer necessary with SML 3 so the check for Steam running was removed, also fixing this.
